name: dungeon-quest # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Dungeon Quest Escape
summary: Navigate treacherous dungeons!
description: Solve puzzles, battle monsters, and uncover hidden secrets to escape dangerous, labyrinthine dungeons.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  dungeon-quest:
    command: bin/dungeon-quest-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  dungeon-quest:
    plugin: dump
    source: .
    organize:
      dungeon-quest-bin: bin/
